
### TESTAR A RAIZ
GET http://localhost:5072

### TESTAR A ROTA DE CADASTRO
POST http://localhost:5072/car
Content-Type: application/json

{
    "Brand": "BMW",
    "Model": "X1",
    "Year": "2024",
    "Plate": "SQL-2024",
    "Color": "Amarelo",
    "ClientId": "1f3e2d70-9988-4ddf-b462-7447d938dec2"
}

### Obter todos os carros
GET http://localhost:5072/cars

### Obter um carro (pelo id)
GET http://localhost:5072/car/

### Remove o carro (pelo id)
DELETE http://localhost:5072/car/6f55d815-f149-4933-bb34-90d8602d63b4