@baseUrl = <http://localhost:5072>

### TESTAR A RAIZ
GET http://localhost:5072

### Criar Serviço
POST http://localhost:5072/carservice
Content-Type: application/json

{
    "Name": "Troca de Pneu",
    "Description": "Troca de Pneu Comum",
    "Price": 400.0,
    "Category": "Troca"
}

### Obter todos os serviços
GET http://localhost:5072/carservices

### Obter um serviço
GET http://localhost:5072/carservice/7cc04f3d-692d-4df1-b64b-73d291fe060a

### Deletar serviço
DELETE http://localhost:5072/carservices/7cc04f3d-692d-4df1-b64b-73d291fe060a