@baseUrl = <http://localhost:5072>

### TESTAR A RAIZ
GET http://localhost:5072

### Criar Serviço
POST http://localhost:5072/carservice
Content-Type: application/json

{
    "Name": "Troca de Óleo",
    "Description": "Troca de Óleo Comum",
    "Price": 230.0,
    "Category": "Troca"
}

### Obter todos os serviços
GET http://localhost:5072/carservices

### Obter um serviço
GET http://localhost:5072/carservice/Troca de Pneu

### Deletar serviço
DELETE http://localhost:5072/carservices/80e32361-e491-41f6-b8fa-c6ecef3d82d2
