
### TESTAR A RAIZ
GET http://localhost:5072

### Criar Cliente
POST http://localhost:5072/client
Content-Type: application/json

{
    "Name": "João Gabriel",
    "Email": "joaogabriel@up.com",
    "Phone": "997297809",
    "Address": "Rua São Cristovão 1850 Casa 03 Curitiba-PR"
}
### Obter todos os clientes
GET http://localhost:5072/clients

### Obter um cliente (pelo id)
### AVISO: LEMBRAR DE INSERIR O ID CORRETO DO USUÁRIO CRIADO PARA O TESTE FUNCIONAR
GET http://localhost:5072/client/0079e009-9461-4f4e-8136-55af4a2ee409
### Atualizar cliente
PUT http://localhost:5072/clients/0079e009-9461-4f4e-8136-55af4a2ee409
Content-Type: application/json

{
    "Name": "Seu Alberto",
    "Email": "seualberto@gmail.com",
    "Phone": "997297809",
    "Address": "Rua dos Ze dos Coquin"
}

### Deletar cliente
DELETE http://localhost:5072/clients/0079e009-9461-4f4e-8136-55af4a2ee409
