
### Cadastrar nova ordem
POST http://localhost:5072/order
Content-Type: application/json

{
    "Nam": "Troca de Óleo para Gol 2012",
    "Description": "Troca de Óleo Comum",
    "CarServiceId": "cd793ecf-8fab-462d-b241-2a6498cca5f8",
    "ClientId": "4358a0e3-76f4-4f71-9b04-a93ab4001698",
    "CarId": "cc834977-7e0b-4cb9-a60e-830afb8d447d"
}

### Obter todas as ordens
GET http://localhost:5072/orders

### Obter uma ordem
GET http://localhost:5072/order/78dd8208-17e1-4d82-b238-d136bfca8aed

### Concluir uma ordem
PUT http://localhost:5072/orders/status/78dd8208-17e1-4d82-b238-d136bfca8aed

### Pedir ordem por cliente
GET http://localhost:5072/orders/client/63e9fcb4-7b6f-4ac7-b3ec-720b315ed38c